name: "CI"

on: [pull_request]

jobs:
  build:
    name: "Build, lint, and test"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Check format"
        run: pnpm format:check

      - name: "Build"
        run: pnpm build

      - name: "Lint"
        run: pnpm lint

      - name: "Test"
        run: pnpm test
